Repository Edirom/Edirom-Online, pull requests merged in 2022-05, with the labels that each got.

#220 Fix run rendering locally
  add/data/xql/getExtendedStaff.xql
  add/data/xqm/util.xqm
  resources/js/verovio-view.js
Labels: Status: needs testing, bugfix

#221 fix filter for measures on page
  add/data/xql/getMeasuresOnPage.xql
Labels: Status: needs testing, bugfix

#225 extend getParts for all MEI verisons
  add/data/xql/getParts.xql
Labels: bugfix

#226 Fix window title unknown
  add/data/xql/getAnnotation.xql
  add/data/xql/getLinkTarget.xql
  add/data/xql/search.xql
  add/data/xqm/annotation.xqm
  add/data/xqm/util.xqm
  add/data/xqm/work.xqm
Labels: Status: needs testing, bugfix, Component: XTechnologies

#224 Fix tei footnotes
  add/data/xql/getText.xql
  add/data/xslt/teiBody2HTML.xsl
  packages/eoTheme/sass/etc/freidi-textView.scss
  packages/eoTheme/sass/etc/freidi-texts.scss
  packages/eoTheme/sass/etc/textViewContent.scss
  resources/css/todo.css
Labels: Status: needs review
