Repository Edirom/Edirom-Online, pull requests merged in 2022-06, with the labels that each got.

#235 CLEANUP: merge edirom_functions.xsl and ediromOnline_functions.xsl
  add/data/xslt/ediromOnline_functions.xsl
  add/data/xslt/edirom_functions.xsl
  add/data/xslt/edirom_source2Print.xsl
  add/data/xslt/meiHead2Print.xsl
Labels: Type: cleanup

#236 Fix relative graphic refs
  add/data/xql/getText.xql
  add/data/xslt/teiBody2HTML.xsl
Labels: Status: needs review

#253 Feature: overlays in OpenSeaDragon
  add/data/xql/getOverlayOnPage.xql
  add/data/xql/getOverlays.xql
  app/controller/window/source/MeasureBasedView.js
  app/controller/window/source/PageBasedView.js
  app/controller/window/source/SourceView.js
  app/view/window/image/OpenSeaDragonViewer.js
  app/view/window/source/MeasureBasedView.js
  app/view/window/source/PageBasedView.js
  app/view/window/source/SourceView.js
Labels: Status: needs work

#254 Fix annotation previews
  add/data/xql/getAnnotationPreviews.xql
  add/data/xql/getPages.xql
  add/data/xqm/annotation.xqm
  app/view/window/AnnotationView.js
  packages/eoTheme/sass/etc/annotation.scss
Labels: bugfix, Status: needs review

#261 Fix/splitted measures in parts
  add/data/xql/getMeasurePage.xql
  add/data/xql/getMeasures.xql
  app/view/window/source/MeasureBasedView.js
Labels: Status: needs testing, bugfix, Priority: High, Status: needs review, View: measureBasedView
