Repository Edirom/Edirom-Online, pull requests merged in 2023-07, with the labels that each got.

#327 add functx 1.0 as package-dependency
  add/data/xql/getAnnotationPreviews.xql
  add/data/xql/getAnnotationsInRendering.xql
  add/data/xql/getAnnotationsOnPage.xql
  add/data/xql/getInternalIdType.xql
  add/data/xql/getMeasure.xql
  add/data/xqm/functx-1.0-nodoc-2007-01.xq
  add/data/xqm/util.xqm
  add/data/xslt/ediromOnline_functions.xsl
  add/data/xslt/functx-1.0-nodoc-2007-01.xsl
  add/data/xslt/teiBody2HTML.xsl
  add/expath-pkg.xml
Labels: Type: cleanup

#321 restructure add section on xqDoc fix typos
  CONTRIBUTING.md
Labels: documentation

#320 Update getAnnotationInfos.xql
  add/data/xql/getAnnotationInfos.xql
Labels: Type: cleanup, Component: XQuery
