Repository Edirom/Edirom-Online, pull requests merged in 2024-12, with the labels that each got.

#292 Feature: reintroduce iframe view
  add/data/xql/getLinkTarget.xql
Labels: Status: needs work

#494 add path to preferences-file
  docs/customize.md
Labels: Area: Documentation

#461 Fix/441 Fail if no language is set
  add/controller.xql
  add/data/xqm/eutil.xqm
Labels: Type: bugfix

#508 Removed "base target blank" in index.xql
  add/index.xql
Labels: Type: bugfix

#514 Update README.md
  README.md
Labels: Area: Documentation
