Repository Edirom/Edirom-Online, pull requests merged in 2024-09, with the labels that each got.

#398 Ftr/358 grayout goto movement
  .github/workflows/pre-release.yml
  add/data/xql/getAnnotationInfos.xql
  add/data/xql/getAnnotationsOnPage.xql
  add/data/xql/getMeasuresOnPage.xql
  add/index.xql
  app/controller/window/source/MeasureBasedView.js
  app/controller/window/source/SourceView.js
  app/view/window/image/OpenSeaDragonViewer.js
  app/view/window/source/MeasureBasedView.js
  app/view/window/source/PageBasedView.js
  app/view/window/source/SourceView.js
  app/view/window/source/VerovioView.js
  app/view/window/text/TextFacsimileSplitView.js
  packages/eoTheme/sass/var/form/field/Base.scss
  packages/eoTheme/sass/var/menu/Menu.scss
Labels: Type: feature request

#413 checkout repository recursively in Github action
  .github/workflows/pre-release.yml
Labels: Type: bugfix, Area: Build & deploy

#414 replace proprietary `exist:serialize` options
  add/data/xql/edirom_printPreview.xql
  add/data/xql/getAnnotationsInRendering.xql
  add/data/xql/getAnnotationsInText.xql
  add/data/xql/getAudioPlayer.xql
  add/data/xql/getChapters.xql
  add/data/xql/getConcordances.xql
  add/data/xql/getEdition.xql
  add/data/xql/getEditionURI.xql
  add/data/xql/getExtendedStaff.xql
  add/data/xql/getHeader.xql
  add/data/xql/getHelp.xql
  add/data/xql/getInternalIdType.xql
  add/data/xql/getLanguageFile.xql
  add/data/xql/getMeasurePage.xql
  add/data/xql/getMeasures.xql
  add/data/xql/getMovementsFirstPage.xql
  add/data/xql/getNavigatorConfig.xql
  add/data/xql/getParts.xql
  add/data/xql/getPreferences.xql
  add/data/xql/getReducedDocument.xql
  add/data/xql/getRendering.xql
  add/data/xql/getSummary.xql
  add/data/xql/getWorkID.xql
  add/data/xql/getWorks.xql
  add/data/xql/getiFrameURL.xql
Labels: Type: cleanup, Area: XQuery

#394 Fix: View TextFacsimileSplitView: add openseadragon as alternative viewer
  app/view/window/text/TextFacsimileSplitView.js
Labels: Type: bugfix

#411 removed unused xql files
  add/data/xql/checkTextGridLogin.xql
  add/data/xql/getAnnotationParticipants.xql
  add/data/xql/getAnnotationsInRendering.xql
  add/data/xql/loginToTextGrid.xql
Labels: Type: cleanup

#422 capture http graphics URLs instead of folder-ups
  add/data/xslt/tei/profiles/edirom-body/teiBody2HTML.xsl
Labels: Type: bugfix

#427 speed improvement for getAnnotationsOnPage
  add/data/xql/getAnnotationsOnPage.xql
Labels: Area: XQuery

#428 Make `eutil:getPreference#2` and `edition:getPreferencesURI#1` more robust
  add/data/xql/getPreferences.xql
  add/data/xqm/edition.xqm
  add/data/xqm/util.xqm
Labels: Type: bugfix, Area: XQuery
