Repository Edirom/Edirom-Online, pull requests merged in 2024-11, with the labels that each got.

#458 fix for #214
  add/data/xql/getInternalIdType.xql
Labels: Type: bugfix, Status: needs review, Area: XQuery

#467 Getting rid of Textgrid
  add/data/xqm/util.xqm
  app/controller/LinkController.js
  testing/XQSuite/eutil-tests.xqm
Labels: Type: cleanup

#477 Update pull_request_template.md
  .github/pull_request_template.md
Labels: Area: Documentation
