Repository Edirom/Edirom-Online, pull requests merged in 2025-01, with the labels that each got.

#519 fix imports
  add/data/xql/getAnnotationsInText.xql
Labels: Type: bugfix, Area: XQuery

#505 fix getLinkTarget for MEI 5 work titles
  add/data/xql/getLinkTarget.xql
Labels: Type: bugfix

#523 ensure to return a string
  add/data/xql/getLinkTarget.xql
Labels: Type: bugfix, Area: XQuery

#522 Update source module and fix `source:getSiglum#1`
  add/data/xqm/source.xqm
Labels: Type: bugfix, Area: XQuery

#527 fix getPreference function
  app/controller/PreferenceController.js
Labels: Type: bugfix, Area: JS

#528 Fix edition details
  add/data/xqm/edition.xqm
Labels: Type: bugfix, Area: XQuery

#531 adjust function signature to allow the empty sequence as return value
  add/data/xql/getAnnotationPreviews.xql
Labels: Type: bugfix, Area: XQuery

#532 fix some annotations-in-text issues
  add/data/xql/getAnnotationsInText.xql
  add/data/xqm/teitext.xqm
Labels: Type: bugfix, Area: XQuery
